apiVersion: v1
kind: Template
metadata:
  name: zabbix-status-api
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: zabbix-status-api
    name: zabbix-status-api
  spec:
    replicas: 3
    selector:
      service: zabbix-status-api
    strategy:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 500Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: zabbix-status-api
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: zabbix-status-api
          ports:
          - containerPort: 80
            protocol: TCP
          env:
            - name: ZABBIX_URL
              valueFrom:
                secretKeyRef:
                  name: zabbix-status-api
                  key: zabbix.url
            - name: ZABBIX_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-status-api
                  key: zabbix.user
            - name: ZABBIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-status-api
                  key: zabbix.password
            - name: HOSTGROUPS
              valueFrom:
                secretKeyRef:
                  name: zabbix-status-api
                  key: hostgroups
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: zabbix-status-api
    name: zabbix-status-api
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: zabbix-status-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: zabbix-status-api
    name: zabbix-status-api
  spec:
    host: ''
    port:
      targetPort: "8080"
    to:
      kind: Service
      name: zabbix-status-api
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE
  value: registry.devshift.net/openshiftio/zabbix-status-api
- name: IMAGE_TAG
  value: latest
